# Generated by Django 4.1.2 on 2022-10-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familiar', '0002_rename_dni_familiar_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiar',
            name='day',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='familiar',
            name='month',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='familiar',
            name='year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
